server:
  port: 8000

spring:
  application:
    name: microservice-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: auth
          uri: http://localhost:8050
          predicates:             
            - Path=/auth/**
        - id: users
          uri: http://localhost:8050
          predicates:             
            - Path=/api/v1/users/**
        - id: events
          uri: http://localhost:8025
          predicates:
            - Path=/api/v1/events/**
        - id: api-docs-user
          uri: http://localhost:8050
          predicates:
            - Path=/v3/api-docs/user
        - id: api-docs-event
          uri: http://localhost:8025
          predicates:
            - Path=/v3/api-docs/event
        - id: api-docs
          uri: http://localhost:8050
          predicates:
            - Path=/v3/api-docs
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            maxAge: 3600
eureka:
  client:
    register-with-eureka: false
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  gateway:
    enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false