server:
  port: 8080

spring:
  application:
    name: microservice-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth
          uri: lb://msvc-user
          predicates:             
            - Path=/auth/**
        - id: users
          uri: lb://msvc-user
          predicates:             
            - Path=/api/v1/users/**
        - id: events
          uri: lb://microservice-event
          predicates:
            - Path=/api/v1/events/**
        - id: api-docs-user
          uri: lb://msvc-user
          predicates:
            - Path=/v3/api-docs/user
        - id: api-docs-event
          uri: lb://microservice-event
          predicates:
            - Path=/v3/api-docs/event
        - id: api-docs
          uri: lb://msvc-user
          predicates:
            - Path=/v3/api-docs
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            maxAge: 3600

eureka:
  instance:
    hostname: gateway-service
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  gateway:
    enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false
